Update CheckPRAndAutoMerge.yaml

diff --git a/.github/workflows/CheckPRAndAutoMerge.yaml b/.github/workflows/CheckPRAndAutoMerge.yaml
--- a/.github/workflows/CheckPRAndAutoMerge.yaml
+++ b/.github/workflows/CheckPRAndAutoMerge.yaml
@@ -28,12 +28,12 @@ jobs:
 
           PR_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_URL)
 
-          echo $PR_RESPONSE
-          # Check if request was successful
-          if [ $? -ne 0 ]; then
-            echo "Failed to fetch PR details."
-            exit 1
-          fi
+          # echo $PR_RESPONSE
+          # # Check if request was successful
+          # if [ $? -ne 0 ]; then
+          #   echo "Failed to fetch PR details."
+          #   exit 1
+          # fi
 
           # Extract merge status
           MERGED=$(echo "$PR_RESPONSE" | jq -r '.merged')
