Update create-release.yaml

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -31,7 +31,7 @@ jobs:
            GH_TOKEN: ${{ github.token }}
         run: |
           TAG_NAME=${{ steps.latest_tag.outputs.tag }}
-          EXISTING_RELEASE=$(gh release list --json tagName)
+          EXISTING_RELEASE=$(gh release view $TAG_NAME --json name --jq ".name" 2>/dev/null || echo "not found")
           echo "$EXISTING_RELEASE"
           eval echo "exists=$EXISTING_RELEASE" >> $GITHUB_OUTPUT
           # if [ "$EXISTING_RELEASE" != "release not found" ]; then
